# -- SOURCE: https://github.com/marketplace/actions/setup-python
# SEE: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: tests
on:
  workflow_dispatch:
  push:
    branches: [ "main", "release/**" ]
  pull_request:
    types: [opened, reopened, review_requested]
    branches: [ "main" ]

jobs:
  test:
    # -- EXAMPLE: runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # PREPARED: os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11", "3.10", "3.9", "pypy-3.10", "pypy-2.7"]
        exclude:
          - os: windows-latest
            python-version: "pypy-2.7"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'py.requirements/*.txt'
      - name: Install Python package dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install --upgrade -r py.requirements/testing.txt
          pip install -e .
      - name: Run tests
        run: pytest
      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test reports
          path: |
            build/testing/report.xml
            build/testing/report.html
        if: ${{ job.status == 'failure' }}
        # MAYBE: if: ${{ always() }}
